// Code generated for student service
// © Student 2026.

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/PabloGolobaro/cosmic_factory/inventory/internal/model"
	"github.com/PabloGolobaro/cosmic_factory/inventory/internal/model/entity"
	"github.com/PabloGolobaro/cosmic_factory/inventory/internal/model/valueobject"
	mock "github.com/stretchr/testify/mock"
)

// NewPartService creates a new instance of PartService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPartService(t interface {
	mock.TestingT
	Cleanup(func())
}) *PartService {
	mock := &PartService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// PartService is an autogenerated mock type for the PartService type
type PartService struct {
	mock.Mock
}

type PartService_Expecter struct {
	mock *mock.Mock
}

func (_m *PartService) EXPECT() *PartService_Expecter {
	return &PartService_Expecter{mock: &_m.Mock}
}

// CommitParts provides a mock function for the type PartService
func (_mock *PartService) CommitParts(ctx context.Context, uuids []string) error {
	ret := _mock.Called(ctx, uuids)

	if len(ret) == 0 {
		panic("no return value specified for CommitParts")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string) error); ok {
		r0 = returnFunc(ctx, uuids)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// PartService_CommitParts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CommitParts'
type PartService_CommitParts_Call struct {
	*mock.Call
}

// CommitParts is a helper method to define mock.On call
//   - ctx context.Context
//   - uuids []string
func (_e *PartService_Expecter) CommitParts(ctx interface{}, uuids interface{}) *PartService_CommitParts_Call {
	return &PartService_CommitParts_Call{Call: _e.mock.On("CommitParts", ctx, uuids)}
}

func (_c *PartService_CommitParts_Call) Run(run func(ctx context.Context, uuids []string)) *PartService_CommitParts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []string
		if args[1] != nil {
			arg1 = args[1].([]string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *PartService_CommitParts_Call) Return(err error) *PartService_CommitParts_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *PartService_CommitParts_Call) RunAndReturn(run func(ctx context.Context, uuids []string) error) *PartService_CommitParts_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type PartService
func (_mock *PartService) Get(context1 context.Context, s string) (entity.Part, error) {
	ret := _mock.Called(context1, s)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 entity.Part
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (entity.Part, error)); ok {
		return returnFunc(context1, s)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) entity.Part); ok {
		r0 = returnFunc(context1, s)
	} else {
		r0 = ret.Get(0).(entity.Part)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(context1, s)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// PartService_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type PartService_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
func (_e *PartService_Expecter) Get(context1 interface{}, s interface{}) *PartService_Get_Call {
	return &PartService_Get_Call{Call: _e.mock.On("Get", context1, s)}
}

func (_c *PartService_Get_Call) Run(run func(context1 context.Context, s string)) *PartService_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *PartService_Get_Call) Return(part entity.Part, err error) *PartService_Get_Call {
	_c.Call.Return(part, err)
	return _c
}

func (_c *PartService_Get_Call) RunAndReturn(run func(context1 context.Context, s string) (entity.Part, error)) *PartService_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type PartService
func (_mock *PartService) List(context1 context.Context, strings []string, partType valueobject.PartType) ([]entity.Part, error) {
	ret := _mock.Called(context1, strings, partType)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []entity.Part
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string, valueobject.PartType) ([]entity.Part, error)); ok {
		return returnFunc(context1, strings, partType)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string, valueobject.PartType) []entity.Part); ok {
		r0 = returnFunc(context1, strings, partType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Part)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []string, valueobject.PartType) error); ok {
		r1 = returnFunc(context1, strings, partType)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// PartService_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type PartService_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - context1 context.Context
//   - strings []string
//   - partType valueobject.PartType
func (_e *PartService_Expecter) List(context1 interface{}, strings interface{}, partType interface{}) *PartService_List_Call {
	return &PartService_List_Call{Call: _e.mock.On("List", context1, strings, partType)}
}

func (_c *PartService_List_Call) Run(run func(context1 context.Context, strings []string, partType valueobject.PartType)) *PartService_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []string
		if args[1] != nil {
			arg1 = args[1].([]string)
		}
		var arg2 valueobject.PartType
		if args[2] != nil {
			arg2 = args[2].(valueobject.PartType)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *PartService_List_Call) Return(parts []entity.Part, err error) *PartService_List_Call {
	_c.Call.Return(parts, err)
	return _c
}

func (_c *PartService_List_Call) RunAndReturn(run func(context1 context.Context, strings []string, partType valueobject.PartType) ([]entity.Part, error)) *PartService_List_Call {
	_c.Call.Return(run)
	return _c
}

// ReleaseParts provides a mock function for the type PartService
func (_mock *PartService) ReleaseParts(ctx context.Context, uuids []string) error {
	ret := _mock.Called(ctx, uuids)

	if len(ret) == 0 {
		panic("no return value specified for ReleaseParts")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string) error); ok {
		r0 = returnFunc(ctx, uuids)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// PartService_ReleaseParts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReleaseParts'
type PartService_ReleaseParts_Call struct {
	*mock.Call
}

// ReleaseParts is a helper method to define mock.On call
//   - ctx context.Context
//   - uuids []string
func (_e *PartService_Expecter) ReleaseParts(ctx interface{}, uuids interface{}) *PartService_ReleaseParts_Call {
	return &PartService_ReleaseParts_Call{Call: _e.mock.On("ReleaseParts", ctx, uuids)}
}

func (_c *PartService_ReleaseParts_Call) Run(run func(ctx context.Context, uuids []string)) *PartService_ReleaseParts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []string
		if args[1] != nil {
			arg1 = args[1].([]string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *PartService_ReleaseParts_Call) Return(err error) *PartService_ReleaseParts_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *PartService_ReleaseParts_Call) RunAndReturn(run func(ctx context.Context, uuids []string) error) *PartService_ReleaseParts_Call {
	_c.Call.Return(run)
	return _c
}

// ReserveParts provides a mock function for the type PartService
func (_mock *PartService) ReserveParts(ctx context.Context, uuids []string) error {
	ret := _mock.Called(ctx, uuids)

	if len(ret) == 0 {
		panic("no return value specified for ReserveParts")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string) error); ok {
		r0 = returnFunc(ctx, uuids)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// PartService_ReserveParts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReserveParts'
type PartService_ReserveParts_Call struct {
	*mock.Call
}

// ReserveParts is a helper method to define mock.On call
//   - ctx context.Context
//   - uuids []string
func (_e *PartService_Expecter) ReserveParts(ctx interface{}, uuids interface{}) *PartService_ReserveParts_Call {
	return &PartService_ReserveParts_Call{Call: _e.mock.On("ReserveParts", ctx, uuids)}
}

func (_c *PartService_ReserveParts_Call) Run(run func(ctx context.Context, uuids []string)) *PartService_ReserveParts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []string
		if args[1] != nil {
			arg1 = args[1].([]string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *PartService_ReserveParts_Call) Return(err error) *PartService_ReserveParts_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *PartService_ReserveParts_Call) RunAndReturn(run func(ctx context.Context, uuids []string) error) *PartService_ReserveParts_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateCompatibility provides a mock function for the type PartService
func (_mock *PartService) ValidateCompatibility(ctx context.Context, slots model.ShipSlots) error {
	ret := _mock.Called(ctx, slots)

	if len(ret) == 0 {
		panic("no return value specified for ValidateCompatibility")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.ShipSlots) error); ok {
		r0 = returnFunc(ctx, slots)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// PartService_ValidateCompatibility_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateCompatibility'
type PartService_ValidateCompatibility_Call struct {
	*mock.Call
}

// ValidateCompatibility is a helper method to define mock.On call
//   - ctx context.Context
//   - slots model.ShipSlots
func (_e *PartService_Expecter) ValidateCompatibility(ctx interface{}, slots interface{}) *PartService_ValidateCompatibility_Call {
	return &PartService_ValidateCompatibility_Call{Call: _e.mock.On("ValidateCompatibility", ctx, slots)}
}

func (_c *PartService_ValidateCompatibility_Call) Run(run func(ctx context.Context, slots model.ShipSlots)) *PartService_ValidateCompatibility_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 model.ShipSlots
		if args[1] != nil {
			arg1 = args[1].(model.ShipSlots)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *PartService_ValidateCompatibility_Call) Return(err error) *PartService_ValidateCompatibility_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *PartService_ValidateCompatibility_Call) RunAndReturn(run func(ctx context.Context, slots model.ShipSlots) error) *PartService_ValidateCompatibility_Call {
	_c.Call.Return(run)
	return _c
}
