logger:
  level: "debug"

grpc:
  host: "localhost"
  port: "50051"

http:
  host: "localhost"
  port: "8080"
  read_header_timeout: "5s"
  read_timeout: "15s"
  write_timeout: "15s"
  idle_timeout: "60s"
  shutdown_timeout: "10s"

pg:
  host: "localhost"
  port: "5432"
  database: "order-service"
  user: "order-service-user"
  password: "order-service-password"
  sslmode: "disable"

inventory:
  host: "localhost"
  port: "50051"
  ping_interval: "10s"
  ping_timeout: "10s"

payment:
  host: "localhost"
  port: "50052"
  ping_interval: "10s"
  ping_timeout: "10s"

kafka:
  brokers: ["localhost:9092"]
  consumer_group: "order-service"
  consume_topic: "assembly.ship-assembled"
  produce_topic: "order.paid"
