logger:
  level: "info"

otel:
  service_name: "order-service"
  endpoint: "otel-collector:4317"

http:
  host: "0.0.0.0"
  port: "8080"

pg:
  host: "postgres-order"
  port: "5432"
  database: "order-service"
  user: "order-service-user"
  password: "order-service-password"
  sslmode: "disable"

inventory:
  host: "inventory-service"
  port: "50051"

payment:
  host: "payment-service"
  port: "50052"

iam:
  host: "iam-service"
  port: "50053"

kafka:
  brokers:
    - "kafka:29092"
  consumer_group: "order-service"
  consume_topic: "assembly.ship-assembled"
  produce_topic: "order.paid"

rate_limit:
  redis_address: "redis-ratelimit:6379"
  rate: 100
  burst: 200
