// Code generated for student service
// © Student 2026.

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/PabloGolobaro/cosmic_factory/order/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// NewOrderService creates a new instance of OrderService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOrderService(t interface {
	mock.TestingT
	Cleanup(func())
}) *OrderService {
	mock := &OrderService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// OrderService is an autogenerated mock type for the OrderService type
type OrderService struct {
	mock.Mock
}

type OrderService_Expecter struct {
	mock *mock.Mock
}

func (_m *OrderService) EXPECT() *OrderService_Expecter {
	return &OrderService_Expecter{mock: &_m.Mock}
}

// Cancel provides a mock function for the type OrderService
func (_mock *OrderService) Cancel(context1 context.Context, s string) error {
	ret := _mock.Called(context1, s)

	if len(ret) == 0 {
		panic("no return value specified for Cancel")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(context1, s)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// OrderService_Cancel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Cancel'
type OrderService_Cancel_Call struct {
	*mock.Call
}

// Cancel is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
func (_e *OrderService_Expecter) Cancel(context1 interface{}, s interface{}) *OrderService_Cancel_Call {
	return &OrderService_Cancel_Call{Call: _e.mock.On("Cancel", context1, s)}
}

func (_c *OrderService_Cancel_Call) Run(run func(context1 context.Context, s string)) *OrderService_Cancel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(arg0, arg1)
	})
	return _c
}

func (_c *OrderService_Cancel_Call) Return(err error) *OrderService_Cancel_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *OrderService_Cancel_Call) RunAndReturn(run func(context1 context.Context, s string) error) *OrderService_Cancel_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function for the type OrderService
func (_mock *OrderService) Create(context1 context.Context, order model.Order) (model.Order, error) {
	ret := _mock.Called(context1, order)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 model.Order
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.Order) (model.Order, error)); ok {
		return returnFunc(context1, order)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.Order) model.Order); ok {
		r0 = returnFunc(context1, order)
	} else {
		r0 = ret.Get(0).(model.Order)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, model.Order) error); ok {
		r1 = returnFunc(context1, order)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// OrderService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type OrderService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - context1 context.Context
//   - order model.Order
func (_e *OrderService_Expecter) Create(context1 interface{}, order interface{}) *OrderService_Create_Call {
	return &OrderService_Create_Call{Call: _e.mock.On("Create", context1, order)}
}

func (_c *OrderService_Create_Call) Run(run func(context1 context.Context, order model.Order)) *OrderService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 model.Order
		if args[1] != nil {
			arg1 = args[1].(model.Order)
		}
		run(arg0, arg1)
	})
	return _c
}

func (_c *OrderService_Create_Call) Return(order1 model.Order, err error) *OrderService_Create_Call {
	_c.Call.Return(order1, err)
	return _c
}

func (_c *OrderService_Create_Call) RunAndReturn(run func(context1 context.Context, order model.Order) (model.Order, error)) *OrderService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type OrderService
func (_mock *OrderService) Get(context1 context.Context, s string) (*model.Order, error) {
	ret := _mock.Called(context1, s)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *model.Order
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*model.Order, error)); ok {
		return returnFunc(context1, s)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *model.Order); ok {
		r0 = returnFunc(context1, s)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Order)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(context1, s)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// OrderService_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type OrderService_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
func (_e *OrderService_Expecter) Get(context1 interface{}, s interface{}) *OrderService_Get_Call {
	return &OrderService_Get_Call{Call: _e.mock.On("Get", context1, s)}
}

func (_c *OrderService_Get_Call) Run(run func(context1 context.Context, s string)) *OrderService_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(arg0, arg1)
	})
	return _c
}

func (_c *OrderService_Get_Call) Return(order *model.Order, err error) *OrderService_Get_Call {
	_c.Call.Return(order, err)
	return _c
}

func (_c *OrderService_Get_Call) RunAndReturn(run func(context1 context.Context, s string) (*model.Order, error)) *OrderService_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Pay provides a mock function for the type OrderService
func (_mock *OrderService) Pay(context1 context.Context, s string, paymentMethod model.PaymentMethod) (string, error) {
	ret := _mock.Called(context1, s, paymentMethod)

	if len(ret) == 0 {
		panic("no return value specified for Pay")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, model.PaymentMethod) (string, error)); ok {
		return returnFunc(context1, s, paymentMethod)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, model.PaymentMethod) string); ok {
		r0 = returnFunc(context1, s, paymentMethod)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, model.PaymentMethod) error); ok {
		r1 = returnFunc(context1, s, paymentMethod)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// OrderService_Pay_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Pay'
type OrderService_Pay_Call struct {
	*mock.Call
}

// Pay is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
//   - paymentMethod model.PaymentMethod
func (_e *OrderService_Expecter) Pay(context1 interface{}, s interface{}, paymentMethod interface{}) *OrderService_Pay_Call {
	return &OrderService_Pay_Call{Call: _e.mock.On("Pay", context1, s, paymentMethod)}
}

func (_c *OrderService_Pay_Call) Run(run func(context1 context.Context, s string, paymentMethod model.PaymentMethod)) *OrderService_Pay_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 model.PaymentMethod
		if args[2] != nil {
			arg2 = args[2].(model.PaymentMethod)
		}
		run(arg0, arg1, arg2)
	})
	return _c
}

func (_c *OrderService_Pay_Call) Return(transactionUUID string, err error) *OrderService_Pay_Call {
	_c.Call.Return(transactionUUID, err)
	return _c
}

func (_c *OrderService_Pay_Call) RunAndReturn(run func(context1 context.Context, s string, paymentMethod model.PaymentMethod) (string, error)) *OrderService_Pay_Call {
	_c.Call.Return(run)
	return _c
}
