
### Create order
# Перед запуском выполни Login в register.http — sessionUuid подтянется автоматически
POST http://localhost:8080/api/v1/orders
Content-Type: application/json
Authorization: Bearer {{sessionUuid}}

{
  "hull_uuid": "550e8400-e29b-41d4-a716-446655440002",
  "engine_uuid": "550e8400-e29b-41d4-a716-446655440003",
  "shield_uuid": "550e8400-e29b-41d4-a716-446655440005",
  "weapon_uuid": "550e8400-e29b-41d4-a716-446655440006"
}

> {%
  client.global.set("orderUuid", response.body.order_uuid);
%}

###

### Pay order
POST http://localhost:8080/api/v1/orders/{{orderUuid}}/pay
Content-Type: application/json
Authorization: Bearer {{sessionUuid}}

{
  "payment_method": "CARD"
}

###

### Cancel order
POST http://localhost:8080/api/v1/orders/{{orderUuid}}/cancel
Content-Type: application/json
Authorization: Bearer {{sessionUuid}}

{}

###

### Get order
GET http://localhost:8080/api/v1/orders/{{orderUuid}}
Authorization: Bearer {{sessionUuid}}

###