### Register — регистрация нового пользователя
### grpcurl -plaintext \
### -d '{"info":{"info":{"login":"testuser"},"password":"password123"}}' \
### localhost:50053 user.v1.UserService/Register
# UserService.Register → возвращает user_uuid
GRPC localhost:50053/user.v1.UserService/Register

{
  "info": {
    "info": {
      "login": "testuser"
    },
    "password": "password123"
  }
}

###

### Login — вход в систему
### grpcurl -plaintext \
### -d '{"login": "testuser","password": "password123"}' \
### localhost:50053 auth.v1.AuthService/Login
# AuthService.Login → возвращает session_uuid
GRPC localhost:50053/auth.v1.AuthService/Login

{
  "login": "testuser",
  "password": "password123"
}

> {%
  client.global.set("sessionUuid", response.body.session_uuid);
  client.log("session_uuid: " + response.body.session_uuid);
%}

###

### Whoami — проверка текущей сессии
# AuthService.Whoami → возвращает сессию и пользователя
GRPC grpc://localhost:50053/auth.v1.AuthService/Whoami

{
  "session_uuid": "{{sessionUuid}}"
}

###

### Logout — завершение сессии
# AuthService.Logout → сессия инвалидируется
GRPC grpc://localhost:50053/auth.v1.AuthService/Logout

{
  "session_uuid": "{{sessionUuid}}"
}

###
