// Code generated for student service
// © Student 2026.

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/PabloGolobaro/cosmic_factory/inventory/internal/model/entity"
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewPartRepository creates a new instance of PartRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPartRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *PartRepository {
	mock := &PartRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// PartRepository is an autogenerated mock type for the PartRepository type
type PartRepository struct {
	mock.Mock
}

type PartRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *PartRepository) EXPECT() *PartRepository_Expecter {
	return &PartRepository_Expecter{mock: &_m.Mock}
}

// Get provides a mock function for the type PartRepository
func (_mock *PartRepository) Get(ctx context.Context, id uuid.UUID) (entity.Part, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 entity.Part
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (entity.Part, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) entity.Part); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(entity.Part)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// PartRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type PartRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *PartRepository_Expecter) Get(ctx interface{}, id interface{}) *PartRepository_Get_Call {
	return &PartRepository_Get_Call{Call: _e.mock.On("Get", ctx, id)}
}

func (_c *PartRepository_Get_Call) Run(run func(ctx context.Context, id uuid.UUID)) *PartRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *PartRepository_Get_Call) Return(part entity.Part, err error) *PartRepository_Get_Call {
	_c.Call.Return(part, err)
	return _c
}

func (_c *PartRepository_Get_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (entity.Part, error)) *PartRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// GetAll provides a mock function for the type PartRepository
func (_mock *PartRepository) GetAll(ctx context.Context) ([]entity.Part, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []entity.Part
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]entity.Part, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []entity.Part); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Part)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// PartRepository_GetAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAll'
type PartRepository_GetAll_Call struct {
	*mock.Call
}

// GetAll is a helper method to define mock.On call
//   - ctx context.Context
func (_e *PartRepository_Expecter) GetAll(ctx interface{}) *PartRepository_GetAll_Call {
	return &PartRepository_GetAll_Call{Call: _e.mock.On("GetAll", ctx)}
}

func (_c *PartRepository_GetAll_Call) Run(run func(ctx context.Context)) *PartRepository_GetAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *PartRepository_GetAll_Call) Return(parts []entity.Part, err error) *PartRepository_GetAll_Call {
	_c.Call.Return(parts, err)
	return _c
}

func (_c *PartRepository_GetAll_Call) RunAndReturn(run func(ctx context.Context) ([]entity.Part, error)) *PartRepository_GetAll_Call {
	_c.Call.Return(run)
	return _c
}

// GetBatch provides a mock function for the type PartRepository
func (_mock *PartRepository) GetBatch(ctx context.Context, ids []uuid.UUID) ([]entity.Part, error) {
	ret := _mock.Called(ctx, ids)

	if len(ret) == 0 {
		panic("no return value specified for GetBatch")
	}

	var r0 []entity.Part
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []uuid.UUID) ([]entity.Part, error)); ok {
		return returnFunc(ctx, ids)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []uuid.UUID) []entity.Part); ok {
		r0 = returnFunc(ctx, ids)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Part)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []uuid.UUID) error); ok {
		r1 = returnFunc(ctx, ids)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// PartRepository_GetBatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBatch'
type PartRepository_GetBatch_Call struct {
	*mock.Call
}

// GetBatch is a helper method to define mock.On call
//   - ctx context.Context
//   - ids []uuid.UUID
func (_e *PartRepository_Expecter) GetBatch(ctx interface{}, ids interface{}) *PartRepository_GetBatch_Call {
	return &PartRepository_GetBatch_Call{Call: _e.mock.On("GetBatch", ctx, ids)}
}

func (_c *PartRepository_GetBatch_Call) Run(run func(ctx context.Context, ids []uuid.UUID)) *PartRepository_GetBatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []uuid.UUID
		if args[1] != nil {
			arg1 = args[1].([]uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *PartRepository_GetBatch_Call) Return(parts []entity.Part, err error) *PartRepository_GetBatch_Call {
	_c.Call.Return(parts, err)
	return _c
}

func (_c *PartRepository_GetBatch_Call) RunAndReturn(run func(ctx context.Context, ids []uuid.UUID) ([]entity.Part, error)) *PartRepository_GetBatch_Call {
	_c.Call.Return(run)
	return _c
}
