// Code generated for student service
// © Student 2026.

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/PabloGolobaro/cosmic_factory/assembly/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// NewProducer creates a new instance of Producer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewProducer(t interface {
	mock.TestingT
	Cleanup(func())
}) *Producer {
	mock := &Producer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Producer is an autogenerated mock type for the Producer type
type Producer struct {
	mock.Mock
}

type Producer_Expecter struct {
	mock *mock.Mock
}

func (_m *Producer) EXPECT() *Producer_Expecter {
	return &Producer_Expecter{mock: &_m.Mock}
}

// PublishShipAssembled provides a mock function for the type Producer
func (_mock *Producer) PublishShipAssembled(ctx context.Context, event model.ShipAssembledEvent) error {
	ret := _mock.Called(ctx, event)

	if len(ret) == 0 {
		panic("no return value specified for PublishShipAssembled")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.ShipAssembledEvent) error); ok {
		r0 = returnFunc(ctx, event)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Producer_PublishShipAssembled_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PublishShipAssembled'
type Producer_PublishShipAssembled_Call struct {
	*mock.Call
}

// PublishShipAssembled is a helper method to define mock.On call
//   - ctx context.Context
//   - event model.ShipAssembledEvent
func (_e *Producer_Expecter) PublishShipAssembled(ctx interface{}, event interface{}) *Producer_PublishShipAssembled_Call {
	return &Producer_PublishShipAssembled_Call{Call: _e.mock.On("PublishShipAssembled", ctx, event)}
}

func (_c *Producer_PublishShipAssembled_Call) Run(run func(ctx context.Context, event model.ShipAssembledEvent)) *Producer_PublishShipAssembled_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 model.ShipAssembledEvent
		if args[1] != nil {
			arg1 = args[1].(model.ShipAssembledEvent)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Producer_PublishShipAssembled_Call) Return(err error) *Producer_PublishShipAssembled_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Producer_PublishShipAssembled_Call) RunAndReturn(run func(ctx context.Context, event model.ShipAssembledEvent) error) *Producer_PublishShipAssembled_Call {
	_c.Call.Return(run)
	return _c
}
