// Code generated for student service
// © Student 2026.

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewShipAssembledService creates a new instance of ShipAssembledService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewShipAssembledService(t interface {
	mock.TestingT
	Cleanup(func())
}) *ShipAssembledService {
	mock := &ShipAssembledService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ShipAssembledService is an autogenerated mock type for the ShipAssembledService type
type ShipAssembledService struct {
	mock.Mock
}

type ShipAssembledService_Expecter struct {
	mock *mock.Mock
}

func (_m *ShipAssembledService) EXPECT() *ShipAssembledService_Expecter {
	return &ShipAssembledService_Expecter{mock: &_m.Mock}
}

// CommitShipParts provides a mock function for the type ShipAssembledService
func (_mock *ShipAssembledService) CommitShipParts(ctx context.Context, orderUUID string) error {
	ret := _mock.Called(ctx, orderUUID)

	if len(ret) == 0 {
		panic("no return value specified for CommitShipParts")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, orderUUID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ShipAssembledService_CommitShipParts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CommitShipParts'
type ShipAssembledService_CommitShipParts_Call struct {
	*mock.Call
}

// CommitShipParts is a helper method to define mock.On call
//   - ctx context.Context
//   - orderUUID string
func (_e *ShipAssembledService_Expecter) CommitShipParts(ctx interface{}, orderUUID interface{}) *ShipAssembledService_CommitShipParts_Call {
	return &ShipAssembledService_CommitShipParts_Call{Call: _e.mock.On("CommitShipParts", ctx, orderUUID)}
}

func (_c *ShipAssembledService_CommitShipParts_Call) Run(run func(ctx context.Context, orderUUID string)) *ShipAssembledService_CommitShipParts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ShipAssembledService_CommitShipParts_Call) Return(err error) *ShipAssembledService_CommitShipParts_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ShipAssembledService_CommitShipParts_Call) RunAndReturn(run func(ctx context.Context, orderUUID string) error) *ShipAssembledService_CommitShipParts_Call {
	_c.Call.Return(run)
	return _c
}
