// Code generated for student service
// © Student 2026.

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/PabloGolobaro/cosmic_factory/inventory/internal/model"
	"github.com/PabloGolobaro/cosmic_factory/inventory/internal/model/entity"
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewPartRepository creates a new instance of PartRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPartRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *PartRepository {
	mock := &PartRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// PartRepository is an autogenerated mock type for the PartRepository type
type PartRepository struct {
	mock.Mock
}

type PartRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *PartRepository) EXPECT() *PartRepository_Expecter {
	return &PartRepository_Expecter{mock: &_m.Mock}
}

// CommitBatch provides a mock function for the type PartRepository
func (_mock *PartRepository) CommitBatch(ctx context.Context, parts []entity.Part) error {
	ret := _mock.Called(ctx, parts)

	if len(ret) == 0 {
		panic("no return value specified for CommitBatch")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []entity.Part) error); ok {
		r0 = returnFunc(ctx, parts)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// PartRepository_CommitBatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CommitBatch'
type PartRepository_CommitBatch_Call struct {
	*mock.Call
}

// CommitBatch is a helper method to define mock.On call
//   - ctx context.Context
//   - parts []entity.Part
func (_e *PartRepository_Expecter) CommitBatch(ctx interface{}, parts interface{}) *PartRepository_CommitBatch_Call {
	return &PartRepository_CommitBatch_Call{Call: _e.mock.On("CommitBatch", ctx, parts)}
}

func (_c *PartRepository_CommitBatch_Call) Run(run func(ctx context.Context, parts []entity.Part)) *PartRepository_CommitBatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []entity.Part
		if args[1] != nil {
			arg1 = args[1].([]entity.Part)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *PartRepository_CommitBatch_Call) Return(err error) *PartRepository_CommitBatch_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *PartRepository_CommitBatch_Call) RunAndReturn(run func(ctx context.Context, parts []entity.Part) error) *PartRepository_CommitBatch_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type PartRepository
func (_mock *PartRepository) Get(ctx context.Context, id uuid.UUID) (entity.Part, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 entity.Part
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (entity.Part, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) entity.Part); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(entity.Part)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// PartRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type PartRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *PartRepository_Expecter) Get(ctx interface{}, id interface{}) *PartRepository_Get_Call {
	return &PartRepository_Get_Call{Call: _e.mock.On("Get", ctx, id)}
}

func (_c *PartRepository_Get_Call) Run(run func(ctx context.Context, id uuid.UUID)) *PartRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *PartRepository_Get_Call) Return(part entity.Part, err error) *PartRepository_Get_Call {
	_c.Call.Return(part, err)
	return _c
}

func (_c *PartRepository_Get_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (entity.Part, error)) *PartRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// GetBatch provides a mock function for the type PartRepository
func (_mock *PartRepository) GetBatch(ctx context.Context, filter model.PartFilter) ([]entity.Part, error) {
	ret := _mock.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for GetBatch")
	}

	var r0 []entity.Part
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.PartFilter) ([]entity.Part, error)); ok {
		return returnFunc(ctx, filter)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.PartFilter) []entity.Part); ok {
		r0 = returnFunc(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Part)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, model.PartFilter) error); ok {
		r1 = returnFunc(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// PartRepository_GetBatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBatch'
type PartRepository_GetBatch_Call struct {
	*mock.Call
}

// GetBatch is a helper method to define mock.On call
//   - ctx context.Context
//   - filter model.PartFilter
func (_e *PartRepository_Expecter) GetBatch(ctx interface{}, filter interface{}) *PartRepository_GetBatch_Call {
	return &PartRepository_GetBatch_Call{Call: _e.mock.On("GetBatch", ctx, filter)}
}

func (_c *PartRepository_GetBatch_Call) Run(run func(ctx context.Context, filter model.PartFilter)) *PartRepository_GetBatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 model.PartFilter
		if args[1] != nil {
			arg1 = args[1].(model.PartFilter)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *PartRepository_GetBatch_Call) Return(parts []entity.Part, err error) *PartRepository_GetBatch_Call {
	_c.Call.Return(parts, err)
	return _c
}

func (_c *PartRepository_GetBatch_Call) RunAndReturn(run func(ctx context.Context, filter model.PartFilter) ([]entity.Part, error)) *PartRepository_GetBatch_Call {
	_c.Call.Return(run)
	return _c
}

// GetBatchForUpdate provides a mock function for the type PartRepository
func (_mock *PartRepository) GetBatchForUpdate(ctx context.Context, filter model.PartFilter) ([]entity.Part, error) {
	ret := _mock.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for GetBatchForUpdate")
	}

	var r0 []entity.Part
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.PartFilter) ([]entity.Part, error)); ok {
		return returnFunc(ctx, filter)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.PartFilter) []entity.Part); ok {
		r0 = returnFunc(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Part)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, model.PartFilter) error); ok {
		r1 = returnFunc(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// PartRepository_GetBatchForUpdate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBatchForUpdate'
type PartRepository_GetBatchForUpdate_Call struct {
	*mock.Call
}

// GetBatchForUpdate is a helper method to define mock.On call
//   - ctx context.Context
//   - filter model.PartFilter
func (_e *PartRepository_Expecter) GetBatchForUpdate(ctx interface{}, filter interface{}) *PartRepository_GetBatchForUpdate_Call {
	return &PartRepository_GetBatchForUpdate_Call{Call: _e.mock.On("GetBatchForUpdate", ctx, filter)}
}

func (_c *PartRepository_GetBatchForUpdate_Call) Run(run func(ctx context.Context, filter model.PartFilter)) *PartRepository_GetBatchForUpdate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 model.PartFilter
		if args[1] != nil {
			arg1 = args[1].(model.PartFilter)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *PartRepository_GetBatchForUpdate_Call) Return(parts []entity.Part, err error) *PartRepository_GetBatchForUpdate_Call {
	_c.Call.Return(parts, err)
	return _c
}

func (_c *PartRepository_GetBatchForUpdate_Call) RunAndReturn(run func(ctx context.Context, filter model.PartFilter) ([]entity.Part, error)) *PartRepository_GetBatchForUpdate_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateReservedBatch provides a mock function for the type PartRepository
func (_mock *PartRepository) UpdateReservedBatch(ctx context.Context, parts []entity.Part) error {
	ret := _mock.Called(ctx, parts)

	if len(ret) == 0 {
		panic("no return value specified for UpdateReservedBatch")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []entity.Part) error); ok {
		r0 = returnFunc(ctx, parts)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// PartRepository_UpdateReservedBatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateReservedBatch'
type PartRepository_UpdateReservedBatch_Call struct {
	*mock.Call
}

// UpdateReservedBatch is a helper method to define mock.On call
//   - ctx context.Context
//   - parts []entity.Part
func (_e *PartRepository_Expecter) UpdateReservedBatch(ctx interface{}, parts interface{}) *PartRepository_UpdateReservedBatch_Call {
	return &PartRepository_UpdateReservedBatch_Call{Call: _e.mock.On("UpdateReservedBatch", ctx, parts)}
}

func (_c *PartRepository_UpdateReservedBatch_Call) Run(run func(ctx context.Context, parts []entity.Part)) *PartRepository_UpdateReservedBatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []entity.Part
		if args[1] != nil {
			arg1 = args[1].([]entity.Part)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *PartRepository_UpdateReservedBatch_Call) Return(err error) *PartRepository_UpdateReservedBatch_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *PartRepository_UpdateReservedBatch_Call) RunAndReturn(run func(ctx context.Context, parts []entity.Part) error) *PartRepository_UpdateReservedBatch_Call {
	_c.Call.Return(run)
	return _c
}
