// Code generated for student service
// © Student 2026.

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/PabloGolobaro/cosmic_factory/order/internal/model"
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewOrderRepository creates a new instance of OrderRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOrderRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *OrderRepository {
	mock := &OrderRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// OrderRepository is an autogenerated mock type for the OrderRepository type
type OrderRepository struct {
	mock.Mock
}

type OrderRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *OrderRepository) EXPECT() *OrderRepository_Expecter {
	return &OrderRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type OrderRepository
func (_mock *OrderRepository) Create(context1 context.Context, order model.Order) (model.Order, error) {
	ret := _mock.Called(context1, order)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 model.Order
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.Order) (model.Order, error)); ok {
		return returnFunc(context1, order)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.Order) model.Order); ok {
		r0 = returnFunc(context1, order)
	} else {
		r0 = ret.Get(0).(model.Order)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, model.Order) error); ok {
		r1 = returnFunc(context1, order)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// OrderRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type OrderRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - context1 context.Context
//   - order model.Order
func (_e *OrderRepository_Expecter) Create(context1 interface{}, order interface{}) *OrderRepository_Create_Call {
	return &OrderRepository_Create_Call{Call: _e.mock.On("Create", context1, order)}
}

func (_c *OrderRepository_Create_Call) Run(run func(context1 context.Context, order model.Order)) *OrderRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 model.Order
		if args[1] != nil {
			arg1 = args[1].(model.Order)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *OrderRepository_Create_Call) Return(order1 model.Order, err error) *OrderRepository_Create_Call {
	_c.Call.Return(order1, err)
	return _c
}

func (_c *OrderRepository_Create_Call) RunAndReturn(run func(context1 context.Context, order model.Order) (model.Order, error)) *OrderRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type OrderRepository
func (_mock *OrderRepository) Delete(context1 context.Context, uUID uuid.UUID) error {
	ret := _mock.Called(context1, uUID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(context1, uUID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// OrderRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type OrderRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - context1 context.Context
//   - uUID uuid.UUID
func (_e *OrderRepository_Expecter) Delete(context1 interface{}, uUID interface{}) *OrderRepository_Delete_Call {
	return &OrderRepository_Delete_Call{Call: _e.mock.On("Delete", context1, uUID)}
}

func (_c *OrderRepository_Delete_Call) Run(run func(context1 context.Context, uUID uuid.UUID)) *OrderRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *OrderRepository_Delete_Call) Return(err error) *OrderRepository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *OrderRepository_Delete_Call) RunAndReturn(run func(context1 context.Context, uUID uuid.UUID) error) *OrderRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type OrderRepository
func (_mock *OrderRepository) Get(context1 context.Context, uUID uuid.UUID) (model.Order, error) {
	ret := _mock.Called(context1, uUID)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 model.Order
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (model.Order, error)); ok {
		return returnFunc(context1, uUID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) model.Order); ok {
		r0 = returnFunc(context1, uUID)
	} else {
		r0 = ret.Get(0).(model.Order)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(context1, uUID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// OrderRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type OrderRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - context1 context.Context
//   - uUID uuid.UUID
func (_e *OrderRepository_Expecter) Get(context1 interface{}, uUID interface{}) *OrderRepository_Get_Call {
	return &OrderRepository_Get_Call{Call: _e.mock.On("Get", context1, uUID)}
}

func (_c *OrderRepository_Get_Call) Run(run func(context1 context.Context, uUID uuid.UUID)) *OrderRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *OrderRepository_Get_Call) Return(order model.Order, err error) *OrderRepository_Get_Call {
	_c.Call.Return(order, err)
	return _c
}

func (_c *OrderRepository_Get_Call) RunAndReturn(run func(context1 context.Context, uUID uuid.UUID) (model.Order, error)) *OrderRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// GetForUpdate provides a mock function for the type OrderRepository
func (_mock *OrderRepository) GetForUpdate(context1 context.Context, uUID uuid.UUID) (model.Order, error) {
	ret := _mock.Called(context1, uUID)

	if len(ret) == 0 {
		panic("no return value specified for GetForUpdate")
	}

	var r0 model.Order
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (model.Order, error)); ok {
		return returnFunc(context1, uUID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) model.Order); ok {
		r0 = returnFunc(context1, uUID)
	} else {
		r0 = ret.Get(0).(model.Order)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(context1, uUID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// OrderRepository_GetForUpdate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetForUpdate'
type OrderRepository_GetForUpdate_Call struct {
	*mock.Call
}

// GetForUpdate is a helper method to define mock.On call
//   - context1 context.Context
//   - uUID uuid.UUID
func (_e *OrderRepository_Expecter) GetForUpdate(context1 interface{}, uUID interface{}) *OrderRepository_GetForUpdate_Call {
	return &OrderRepository_GetForUpdate_Call{Call: _e.mock.On("GetForUpdate", context1, uUID)}
}

func (_c *OrderRepository_GetForUpdate_Call) Run(run func(context1 context.Context, uUID uuid.UUID)) *OrderRepository_GetForUpdate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *OrderRepository_GetForUpdate_Call) Return(order model.Order, err error) *OrderRepository_GetForUpdate_Call {
	_c.Call.Return(order, err)
	return _c
}

func (_c *OrderRepository_GetForUpdate_Call) RunAndReturn(run func(context1 context.Context, uUID uuid.UUID) (model.Order, error)) *OrderRepository_GetForUpdate_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type OrderRepository
func (_mock *OrderRepository) Update(context1 context.Context, order model.Order) error {
	ret := _mock.Called(context1, order)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.Order) error); ok {
		r0 = returnFunc(context1, order)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// OrderRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type OrderRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - context1 context.Context
//   - order model.Order
func (_e *OrderRepository_Expecter) Update(context1 interface{}, order interface{}) *OrderRepository_Update_Call {
	return &OrderRepository_Update_Call{Call: _e.mock.On("Update", context1, order)}
}

func (_c *OrderRepository_Update_Call) Run(run func(context1 context.Context, order model.Order)) *OrderRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 model.Order
		if args[1] != nil {
			arg1 = args[1].(model.Order)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *OrderRepository_Update_Call) Return(err error) *OrderRepository_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *OrderRepository_Update_Call) RunAndReturn(run func(context1 context.Context, order model.Order) error) *OrderRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}
