// Code generated for student service
// © Student 2026.

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/PabloGolobaro/cosmic_factory/order/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// NewOrderPaidProducer creates a new instance of OrderPaidProducer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOrderPaidProducer(t interface {
	mock.TestingT
	Cleanup(func())
}) *OrderPaidProducer {
	mock := &OrderPaidProducer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// OrderPaidProducer is an autogenerated mock type for the OrderPaidProducer type
type OrderPaidProducer struct {
	mock.Mock
}

type OrderPaidProducer_Expecter struct {
	mock *mock.Mock
}

func (_m *OrderPaidProducer) EXPECT() *OrderPaidProducer_Expecter {
	return &OrderPaidProducer_Expecter{mock: &_m.Mock}
}

// PublishOrderPaid provides a mock function for the type OrderPaidProducer
func (_mock *OrderPaidProducer) PublishOrderPaid(ctx context.Context, event model.OrderPaidEvent) error {
	ret := _mock.Called(ctx, event)

	if len(ret) == 0 {
		panic("no return value specified for PublishOrderPaid")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.OrderPaidEvent) error); ok {
		r0 = returnFunc(ctx, event)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// OrderPaidProducer_PublishOrderPaid_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PublishOrderPaid'
type OrderPaidProducer_PublishOrderPaid_Call struct {
	*mock.Call
}

// PublishOrderPaid is a helper method to define mock.On call
//   - ctx context.Context
//   - event model.OrderPaidEvent
func (_e *OrderPaidProducer_Expecter) PublishOrderPaid(ctx interface{}, event interface{}) *OrderPaidProducer_PublishOrderPaid_Call {
	return &OrderPaidProducer_PublishOrderPaid_Call{Call: _e.mock.On("PublishOrderPaid", ctx, event)}
}

func (_c *OrderPaidProducer_PublishOrderPaid_Call) Run(run func(ctx context.Context, event model.OrderPaidEvent)) *OrderPaidProducer_PublishOrderPaid_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 model.OrderPaidEvent
		if args[1] != nil {
			arg1 = args[1].(model.OrderPaidEvent)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *OrderPaidProducer_PublishOrderPaid_Call) Return(err error) *OrderPaidProducer_PublishOrderPaid_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *OrderPaidProducer_PublishOrderPaid_Call) RunAndReturn(run func(ctx context.Context, event model.OrderPaidEvent) error) *OrderPaidProducer_PublishOrderPaid_Call {
	_c.Call.Return(run)
	return _c
}
