// Code generated for student service
// © Student 2026.

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/PabloGolobaro/cosmic_factory/order/internal/model"
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewOrderItemRepository creates a new instance of OrderItemRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOrderItemRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *OrderItemRepository {
	mock := &OrderItemRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// OrderItemRepository is an autogenerated mock type for the OrderItemRepository type
type OrderItemRepository struct {
	mock.Mock
}

type OrderItemRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *OrderItemRepository) EXPECT() *OrderItemRepository_Expecter {
	return &OrderItemRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type OrderItemRepository
func (_mock *OrderItemRepository) Create(context1 context.Context, orderItem model.OrderItem) (model.OrderItem, error) {
	ret := _mock.Called(context1, orderItem)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 model.OrderItem
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.OrderItem) (model.OrderItem, error)); ok {
		return returnFunc(context1, orderItem)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.OrderItem) model.OrderItem); ok {
		r0 = returnFunc(context1, orderItem)
	} else {
		r0 = ret.Get(0).(model.OrderItem)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, model.OrderItem) error); ok {
		r1 = returnFunc(context1, orderItem)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// OrderItemRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type OrderItemRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - context1 context.Context
//   - orderItem model.OrderItem
func (_e *OrderItemRepository_Expecter) Create(context1 interface{}, orderItem interface{}) *OrderItemRepository_Create_Call {
	return &OrderItemRepository_Create_Call{Call: _e.mock.On("Create", context1, orderItem)}
}

func (_c *OrderItemRepository_Create_Call) Run(run func(context1 context.Context, orderItem model.OrderItem)) *OrderItemRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 model.OrderItem
		if args[1] != nil {
			arg1 = args[1].(model.OrderItem)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *OrderItemRepository_Create_Call) Return(orderItem1 model.OrderItem, err error) *OrderItemRepository_Create_Call {
	_c.Call.Return(orderItem1, err)
	return _c
}

func (_c *OrderItemRepository_Create_Call) RunAndReturn(run func(context1 context.Context, orderItem model.OrderItem) (model.OrderItem, error)) *OrderItemRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type OrderItemRepository
func (_mock *OrderItemRepository) Delete(ctx context.Context, id uuid.UUID) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// OrderItemRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type OrderItemRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *OrderItemRepository_Expecter) Delete(ctx interface{}, id interface{}) *OrderItemRepository_Delete_Call {
	return &OrderItemRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *OrderItemRepository_Delete_Call) Run(run func(ctx context.Context, id uuid.UUID)) *OrderItemRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *OrderItemRepository_Delete_Call) Return(err error) *OrderItemRepository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *OrderItemRepository_Delete_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) error) *OrderItemRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type OrderItemRepository
func (_mock *OrderItemRepository) Get(context1 context.Context, uUID uuid.UUID) (model.OrderItem, error) {
	ret := _mock.Called(context1, uUID)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 model.OrderItem
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (model.OrderItem, error)); ok {
		return returnFunc(context1, uUID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) model.OrderItem); ok {
		r0 = returnFunc(context1, uUID)
	} else {
		r0 = ret.Get(0).(model.OrderItem)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(context1, uUID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// OrderItemRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type OrderItemRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - context1 context.Context
//   - uUID uuid.UUID
func (_e *OrderItemRepository_Expecter) Get(context1 interface{}, uUID interface{}) *OrderItemRepository_Get_Call {
	return &OrderItemRepository_Get_Call{Call: _e.mock.On("Get", context1, uUID)}
}

func (_c *OrderItemRepository_Get_Call) Run(run func(context1 context.Context, uUID uuid.UUID)) *OrderItemRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *OrderItemRepository_Get_Call) Return(orderItem model.OrderItem, err error) *OrderItemRepository_Get_Call {
	_c.Call.Return(orderItem, err)
	return _c
}

func (_c *OrderItemRepository_Get_Call) RunAndReturn(run func(context1 context.Context, uUID uuid.UUID) (model.OrderItem, error)) *OrderItemRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// ListByOrder provides a mock function for the type OrderItemRepository
func (_mock *OrderItemRepository) ListByOrder(ctx context.Context, orderUUID uuid.UUID) ([]model.OrderItem, error) {
	ret := _mock.Called(ctx, orderUUID)

	if len(ret) == 0 {
		panic("no return value specified for ListByOrder")
	}

	var r0 []model.OrderItem
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]model.OrderItem, error)); ok {
		return returnFunc(ctx, orderUUID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) []model.OrderItem); ok {
		r0 = returnFunc(ctx, orderUUID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.OrderItem)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, orderUUID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// OrderItemRepository_ListByOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByOrder'
type OrderItemRepository_ListByOrder_Call struct {
	*mock.Call
}

// ListByOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - orderUUID uuid.UUID
func (_e *OrderItemRepository_Expecter) ListByOrder(ctx interface{}, orderUUID interface{}) *OrderItemRepository_ListByOrder_Call {
	return &OrderItemRepository_ListByOrder_Call{Call: _e.mock.On("ListByOrder", ctx, orderUUID)}
}

func (_c *OrderItemRepository_ListByOrder_Call) Run(run func(ctx context.Context, orderUUID uuid.UUID)) *OrderItemRepository_ListByOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *OrderItemRepository_ListByOrder_Call) Return(orderItems []model.OrderItem, err error) *OrderItemRepository_ListByOrder_Call {
	_c.Call.Return(orderItems, err)
	return _c
}

func (_c *OrderItemRepository_ListByOrder_Call) RunAndReturn(run func(ctx context.Context, orderUUID uuid.UUID) ([]model.OrderItem, error)) *OrderItemRepository_ListByOrder_Call {
	_c.Call.Return(run)
	return _c
}
