// Code generated for student service
// © Student 2026.

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewIAMClient creates a new instance of IAMClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIAMClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *IAMClient {
	mock := &IAMClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// IAMClient is an autogenerated mock type for the IAMClient type
type IAMClient struct {
	mock.Mock
}

type IAMClient_Expecter struct {
	mock *mock.Mock
}

func (_m *IAMClient) EXPECT() *IAMClient_Expecter {
	return &IAMClient_Expecter{mock: &_m.Mock}
}

// Authorize provides a mock function for the type IAMClient
func (_mock *IAMClient) Authorize(ctx context.Context, action string, ownerUUID uuid.UUID) error {
	ret := _mock.Called(ctx, action, ownerUUID)

	if len(ret) == 0 {
		panic("no return value specified for Authorize")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, action, ownerUUID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// IAMClient_Authorize_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Authorize'
type IAMClient_Authorize_Call struct {
	*mock.Call
}

// Authorize is a helper method to define mock.On call
//   - ctx context.Context
//   - action string
//   - ownerUUID uuid.UUID
func (_e *IAMClient_Expecter) Authorize(ctx interface{}, action interface{}, ownerUUID interface{}) *IAMClient_Authorize_Call {
	return &IAMClient_Authorize_Call{Call: _e.mock.On("Authorize", ctx, action, ownerUUID)}
}

func (_c *IAMClient_Authorize_Call) Run(run func(ctx context.Context, action string, ownerUUID uuid.UUID)) *IAMClient_Authorize_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *IAMClient_Authorize_Call) Return(err error) *IAMClient_Authorize_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *IAMClient_Authorize_Call) RunAndReturn(run func(ctx context.Context, action string, ownerUUID uuid.UUID) error) *IAMClient_Authorize_Call {
	_c.Call.Return(run)
	return _c
}
