// Code generated for student service
// © Student 2026.

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/PabloGolobaro/cosmic_factory/order/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// NewPaymentClient creates a new instance of PaymentClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPaymentClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *PaymentClient {
	mock := &PaymentClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// PaymentClient is an autogenerated mock type for the PaymentClient type
type PaymentClient struct {
	mock.Mock
}

type PaymentClient_Expecter struct {
	mock *mock.Mock
}

func (_m *PaymentClient) EXPECT() *PaymentClient_Expecter {
	return &PaymentClient_Expecter{mock: &_m.Mock}
}

// PayOrder provides a mock function for the type PaymentClient
func (_mock *PaymentClient) PayOrder(ctx context.Context, uuid string, paymentMethod model.PaymentMethod) error {
	ret := _mock.Called(ctx, uuid, paymentMethod)

	if len(ret) == 0 {
		panic("no return value specified for PayOrder")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, model.PaymentMethod) error); ok {
		r0 = returnFunc(ctx, uuid, paymentMethod)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// PaymentClient_PayOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PayOrder'
type PaymentClient_PayOrder_Call struct {
	*mock.Call
}

// PayOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - uuid string
//   - paymentMethod model.PaymentMethod
func (_e *PaymentClient_Expecter) PayOrder(ctx interface{}, uuid interface{}, paymentMethod interface{}) *PaymentClient_PayOrder_Call {
	return &PaymentClient_PayOrder_Call{Call: _e.mock.On("PayOrder", ctx, uuid, paymentMethod)}
}

func (_c *PaymentClient_PayOrder_Call) Run(run func(ctx context.Context, uuid string, paymentMethod model.PaymentMethod)) *PaymentClient_PayOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 model.PaymentMethod
		if args[2] != nil {
			arg2 = args[2].(model.PaymentMethod)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *PaymentClient_PayOrder_Call) Return(err error) *PaymentClient_PayOrder_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *PaymentClient_PayOrder_Call) RunAndReturn(run func(ctx context.Context, uuid string, paymentMethod model.PaymentMethod) error) *PaymentClient_PayOrder_Call {
	_c.Call.Return(run)
	return _c
}
